---
name: 'Lint, Unit & Integration Tests'

"on":
  pull_request:

jobs:
  lint-unit:
    uses: test-kitchen/.github/.github/workflows/lint-unit.yml@main

  integration-windows:
    name: Windows ${{matrix.suite}} ${{matrix.os}}
    runs-on: windows-latest
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        suite: [default]
        os: [ubuntu-24.04]
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} -l debug

  integration-linux:
    name: Linux ${{matrix.suite}} ${{matrix.os}}
    runs-on: ubuntu-latest
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        suite:
          - default
          - no-build-context
          - arm64
          - amd64
          - inspec
        os:
          - amazonlinux-2023
          - ubuntu-2204
          - ubuntu-2404
          - fedora-latest
          - almalinux-9
          - rockylinux-9
          - debian-12
          - opensuse-15
          - dockerfile
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} -l debug

  integration-capabilities:
    name: Linux ${{matrix.suite}} ${{matrix.os}}
    runs-on: ubuntu-latest
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        suite:
          - capabilities
        os: [debian-12, ubuntu-2204, ubuntu-2404]
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} -l debug
